### ISSUE TITLE
BUG - macOS - Sound aliases throw an error

### ISSUE THREAD

**Issue by Emrix** [osiris-project/quartz#11]
**Issue**
When attempting to play a file in the sounds folder that is an alias to a file located somewhere else in the system, an error is thrown, probably because it doesn't try to follow through on that alias, but just tries to read the alias file itself.

**Steps to Reproduce**
1. Using macOS, make sure you have an alias in the sounds folder
2. Start Quartz
2. Attempt to play the sound alias
3. Notice the error thrown

**Additional Info**
The error is as follows:
`Traceback (most recent call last):
  File "/Users/mattricks/Desktop/quartz-dev/quartz.py", line 44, in <module>
    terminalDriver()
  File "/Users/mattricks/Desktop/quartz-dev/quartz.py", line 33, in terminalDriver
    soundPlayer.playSound(getFile(lineIn))
  File "/Users/mattricks/Desktop/quartz-dev/soundPlayer.py", line 25, in playSound
    waveObj = sa.WaveObject.from_wave_file(fileName)
  File "/usr/local/lib/python3.9/site-packages/simpleaudio/shiny.py", line 24, in from_wave_file
    wave_read = wave.open(wave_file, 'rb')
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/wave.py", line 509, in open
    return Wave_read(f)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/wave.py", line 163, in __init__
    self.initfp(f)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/wave.py", line 130, in initfp
    raise Error('file does not start with RIFF id')
wave.Error: file does not start with RIFF id`

**Comment by Emrix** [comment]
I don't think we actually need to worry about this issue personally, I mostly just logged it so that we have historical information on what was tested.
